import * as React from 'react';
import { Share2, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

interface SharePanelProps {
  poem: string | null;
  appName: string;
  imageUrl: string | null; // For potential image sharing in future
}

export function SharePanel({ poem, appName, imageUrl }: SharePanelProps) {
  const { toast } = useToast();

  const handleShare = async () => {
    const shareText = `Check out this poem generated by ${appName}:\n\n${poem}\n\nInspired by an image.`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${appName} - Poem`,
          text: shareText,
          // url: window.location.href, // Can share current page URL
        });
      } catch (error) {
        console.error('Error sharing:', error);
        toast({
          title: "Sharing failed",
          description: "Could not share using the native share dialog.",
          variant: "destructive",
        });
      }
    } else {
      // Fallback for browsers that don't support Web Share API
      handleCopyToClipboard(shareText, "Poem copied to clipboard!");
    }
  };

  const handleCopyToClipboard = (textToCopy: string | null, message: string) => {
    if (!textToCopy) return;
    navigator.clipboard.writeText(textToCopy).then(() => {
      toast({
        title: "Copied!",
        description: message,
      });
    }).catch(err => {
      console.error('Failed to copy:', err);
      toast({
        title: "Copy failed",
        description: "Could not copy text to clipboard.",
        variant: "destructive",
      });
    });
  };

  if (!poem) return null;

  return (
    <div className="mt-6 flex flex-col sm:flex-row gap-3">
      <Button onClick={handleShare} variant="outline" className="flex-1">
        <Share2 className="mr-2 h-4 w-4" />
        Share Poem
      </Button>
      <Button 
        onClick={() => handleCopyToClipboard(poem, "Poem copied to clipboard!")} 
        variant="outline" 
        className="flex-1"
      >
        <Copy className="mr-2 h-4 w-4" />
        Copy Poem
      </Button>
    </div>
  );
}
